name: my_env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - cartopy==0.21.0
  - proj==9.1.0 # Required to build cartopy (can't be installed with pip)
  - flask==2.1.3
  - pandas==1.4.4
  - pip=22.2.2
  - pip:
    - flagpy==1.0.3
    - gunicorn==20.1.0
    
